### ISSUE TITLE
Inquiry about the status of this driver

### ISSUE THREAD

**Issue by mjtbrady** [OpenNebula/addon-drbdmanage#12]
I started looking at OpenNebula and the DRBDManage driver last week and am a bit confused as to the status of this driver and am wondering if I am missing something.

From my testing so far, the driver:

1. Does not support contextualisation because tm/drbdmanage/context does not exist
2. Does not support live migration because tm/drbdmanage/premigrate and tm/drbdmanage/postmigrate do not do anything.  They are both one line scripts that only contain "exit 0".
3. If you do try to do a live migrate, it will fail because of the above and then the failure fails because tm/drbdmanage/failmigrate does not exist.
4. Does not support volatile volumes because tm/drbdmanage/mkimage (and mkswap) do not exist.
5. Terminating (and possibly other operations) a VM fails due to a bug in tm/drdbmanage/delete
6. Migrating (not live) a VM fails with bash syntax errors.
7. There are other errors with deploying volumes that I haven't figured out.

Does the above reflect that status of the development of this driver (at least for the unimplemented functions) or am I missing something here?

If the above is correct and these things really do need fixing I do have fixes for some of them and I am happy to contribute.  I will have to figure out how to use GITHub first, but that is long over due.

Thanks

Mike

**Comment by haySwim** [comment]
> I started looking at OpenNebula and the DRBDManage driver last week and am a bit confused as to the status of this driver and am wondering if I am missing something.
> 

This driver is used in production.

> From my testing so far, the driver:
> 
>     Does not support contextualisation because tm/drbdmanage/context does not exist

This is a datastore driver. Reading through the README again, it seems I failed to make this point. You should be using nfs for the system datastore. 

>     Does not support live migration because tm/drbdmanage/premigrate and tm/drbdmanage/postmigrate do not do anything. They are both one line scripts that only contain "exit 0".

ONE doesn't run these actions on datastore drivers, information on how to enable live migrations can be found here:

https://github.com/OpenNebula/addon-drbdmanage#optional-attributes

>     If you do try to do a live migrate, it will fail because of the above and then the failure fails because tm/drbdmanage/failmigrate does not exist.

This is a system datastore thing.

>     Does not support volatile volumes because tm/drbdmanage/mkimage (and mkswap) do not exist.

This is a system datastore thing as well. We decided not to implement the actions that would enable us to be a system datastore because the underlying storage, i.e. block devices, especially replicated ones, do not really make sense when dealing with small, volatile files/images.

>     Terminating (and possibly other operations) a VM fails due to a bug in tm/drdbmanage/delete

Can you elaborate? What versions of DRBD, drbd-utils, DRBD Manage, are you running? Which distribution are you using? grep the kernel logs for "Beginning delete action." and paste or link the result.

>     Migrating (not live) a VM fails with bash syntax errors.

Can you post the errors? Also the kernel log should contain output from DRBD, DRBD Manage, and the driver.  There are a couple of driver actions that handle this, but you should see the drivers name in the kernel logs around the same time, post or link that please.

>     There are other errors with deploying volumes that I haven't figured out.
> 

I'd be happy to help, or direct you to help with more information.

**Comment by haySwim** [comment]
> If the above is correct and these things really do need fixing I do have fixes for some of them and I am happy to contribute. I will have to figure out how to use GITHub first, but that is long over due.

Sure, we don't use gh extensively so it's been a learning experience.

I'm not sure about other maintainers, but if you have an issue with a prepossessed fix, I'd prefer them to have their own issue/pr. I think this makes historical reviews of the conversations much easier and lets issues that are easy/non-controversial get through a bit quicker.

**Comment by mjtbrady** [comment]
Thanks for the response.

As I think that you have guessed, I have been trying to use the DRBDMange driver for both the image and system datastores, which explains most if not all the issues that I have been seeing.


I will go away and figure out how to use a different system datastore and come back if I need to then.

**Comment by haySwim** [comment]
No problem! I'm glad you asked, I didn't realize I left the system vs. datastore driver discussion out of the documentation.
