### ISSUE TITLE
Need help with set up

### ISSUE THREAD

**Issue by mjtbrady** [OpenNebula/addon-drbdmanage#13]
After finding that I was doing things completely wrong with a DRBDManage system datastore I have started again (at least from the datastore perspective), but I believe that I am having issues with creating the image datastore as detailed below, so I am obviously still missing something.

The environment is:
- Three machines one01, kvm08 and kvm12.  kvm08 and kvm12 are physical boxes, one01 is a VM on kvm08 and is the frontend.
- All three machines are up to date CentOS 7.3.
- All three machines have the latest DRBD packages created from source.
 ```
[root@one01 ~]# rpm -qa | grep -i drbd
drbd-pacemaker-9.0.0-1.el7.centos.x86_64
drbd-utils-9.0.0-1.el7.centos.x86_64
drbd-xen-9.0.0-1.el7.centos.x86_64
drbd-udev-9.0.0-1.el7.centos.x86_64
drbdmanage-0.99.5-1.noarch
kmod-drbd-9.0.8_3.10.0_514.26.2-1.el7.centos.x86_64
drbd-bash-completion-9.0.0-1.el7.centos.x86_64
drbd-9.0.0-1.el7.centos.x86_64
```
- OpenNebula 5.4
- DRBDManage cluster is functional in that all the nodes show up and I can deploy resources using drbdmanage.  one01 (the frontend) was initialised with no storage.
```
 [root@one01 ~]# drbdmanage list-nodes --machine
kvm08.devnull.net.nz,4,192.168.48.23,1073741824,1071164843,drbdctrl|storage,N/A
kvm12.devnull.net.nz,4,192.168.48.24,1073741824,1071164843,drbdctrl|storage,N/A
one01.devnull.net.nz,4,192.168.48.25,0,0,drbdctrl,N/A
```
- The frontend is installed and kvm08 and kvm12 are added as nodes and are working at least to the level that OpenNebula monitoring is working for them.
- I have added a drbdmanage image datastore with the following file definition
```
NAME = drbdmanage_images
DS_MAD = drbdmanage
TM_MAD = drbdmanage
DRBD_DEPLOYMENT_NODES = "kvm08.devnull.net.nz kvm12.devnull.net.nz"
BRIDGE_LIST = "one01.devnull.net.nz kvm08.devnull.net.nz kvm12.devnull.net.nz"
DRBD_SUPPORT_LIVE_MIGRATION = yes
```
- The datastore appears to have been created
```
[root@one01 one]# onedatastore list
  ID NAME                SIZE AVAIL CLUSTERS     IMAGES TYPE DS      TM      STAT
   0 system                 - -     0                 0 sys  -       ssh     on  
   1 default              30G 91%   0                 0 img  fs      ssh     on  
   2 files                30G 91%   0                 0 fil  fs      ssh     on  
 110 drbdmanage_im      1024G 100%  0,100             3 img  drbdman drbdman on  
[root@one01 one]# onedatastore show 110
DATASTORE 110 INFORMATION                                                       
ID             : 110                 
NAME           : drbdmanage_images   
USER           : oneadmin            
GROUP          : oneadmin            
CLUSTERS       : 0,100               
TYPE           : IMAGE               
DS_MAD         : drbdmanage          
TM_MAD         : drbdmanage          
BASE PATH      : /var/lib/one/datastores/110
DISK_TYPE      : FILE                
STATE          : READY               

DATASTORE CAPACITY                                                              
TOTAL:         : 1024G               
FREE:          : 1021.5G             
USED:          : 0M                  
LIMIT:         : -                   

PERMISSIONS                                                                     
OWNER          : um-                 
GROUP          : u--                 
OTHER          : ---                 

DATASTORE TEMPLATE                                                              
ALLOW_ORPHANS="NO"
BRIDGE_LIST="one01.devnull.net.nz kvm08.devnull.net.nz kvm12.devnull.net.nz"
CLONE_TARGET="SELF"
DISK_TYPE="FILE"
DRBD_DEPLOYMENT_NODES="kvm08.devnull.net.nz kvm12.devnull.net.nz"
DRBD_SUPPORT_LIVE_MIGRATION="yes"
DS_MAD="drbdmanage"
LN_TARGET="NONE"
RESTRICTED_DIRS="/"
SAFE_DIRS="/var/tmp"
TM_MAD="drbdmanage"

IMAGES         
19             
20             
21 
```
- And I have added a few images to the datastore through Sunstone which seem to have succeeded.
```
[root@one01 one]# oneimage list
  ID USER       GROUP      NAME            DATASTORE     SIZE TYPE PER STAT RVMS
  19 oneadmin   oneadmin   CentOS-7-x86_64 drbdmanage    680M CD    No rdy     0
  20 oneadmin   oneadmin   pfSense-CE-2.4. drbdmanage    573M CD    No rdy     0
  21 oneadmin   oneadmin   Copy of pfSense drbdmanage    573M CD    No rdy     0
```
At this point I think (possibly incorrectly) that there are two problems:
- Firstly the datastore directory (/var/lib/one/datastores/110) doesn't exist on any of the machines.  It should right?
- And secondly, although the the image additions did not report any errors the entries from /var/log/messages in the attached file suggest otherwise?  There are both drdbmanaged errors and a ruby crash.
[image_create_failure.txt](https://github.com/OpenNebula/addon-drbdmanage/files/1192612/image_create_failure.txt)

I have more questions about how to set up the system datastore, but figured that I should make sure I had this part correct first.

Thanks
Mike

**Comment by haySwim** [comment]
As for the `/var/lib/one/datastores/110` thing, it's honestly been a while since I had to look at ONE implementation details like that, but it's possible that won't be created until a VM uses it.

Seems like DRBD Manage might have recovered from those errors. You can do `drbdmanage list-assignments` to see where/if resources were deployed. The driver tries to make sure that the volume is ready to be used on at lease one node before exiting:
`Aug  2 12:56:38 one01 addon-drbdmanage: datastore-cp: [26083]: kvm08.devnull.net.nz is ready for IO operations on /dev/drbd173`

I can't speak to the ruby error other than it expected `/var/tmp/713031680-CentOS-7-x86_64-Minimal-1611iso` to exist and it didn't. That's a ONE thing as well.

**Comment by JOJ0** [comment]
Hi,
are you using an nfs share for /var/lib/one? 
hence the system store is also nfs?
If yes the TM driver of the system store should be set to "shared". your "one datastore list" shows that it is set to ssh. you can change it using "one datastore update <id>"
hope that helps
Jojo

**Comment by mjtbrady** [comment]
1. At no point does the drbdmanage Image datastore show up in /var/lib/one/datastores, but it seems to be working.
2. The ruby error almost looks like it is trying to add the image twice, but it does it successfully anyway.
3. No, no nfs.  The datastores 0, 1 and 2 were just the default ones from the initial install.  I wanted to make sure that the Image datastore was correct first before doing anything else.
4. drbdmanage continues to log many "ERROR      Signal creation failed, unhandled exception encountered" messages, which isn't confidence building.

I have moved forward with this is inspite of the errors and now have something that sort of works.  I have an error with cloning that I will open a separate issue for.

**Comment by JOJ0** [comment]
Hi again,

1. i checked this, it is supposed to be like that. drbdmanage image store does not create this subdirectory.


2. did you actually check if your image is really successfully copied to the drbd device? is your centos image there and reads like one? Seems like your drbd device was correctly built, but the iso image to upload could not be found:

Aug  2 12:57:04 one01 ruby: 2017-08-02 12:57:04 - Errno::ENOENT - No such file or directory - /var/tmp/713031680-CentOS-7-x86_64-Minimal-1611iso:

did you execute the "oneimage create" command on the frontend or on one of your two hypervisors?
(yes you can execute one.... commands from other hosts as well, if you set your shell environment right :-)

or did you upload it using the gui?

please try if you can successfully upload an image from the commandline. the path of the image to be uploaded should always be available on the frontend node, and not on the node you are executing the oneimage command from!


3. alright I understand. It just caught my attention because the default driver types of these 3 default datastores were changed to ssh with release 5.2, before they were set to shared. I always have used the shared datastore type for system. This got me into trouble once.

I am unsure if addon-drbdmanage is compatible with a tm-ssh system datastore, I never used it and probably can't help you with it.

I would recommend you set up an nfs share on your frontend. In short it works like that: You instantiate a VM from a template image that is stored on a drbd device; a drbd device will be cloned from there, and a symbolic link to that device will be created inside the /var/lib/one/datastores/0/vmid/ directory pointing to the cloned drbd device. no actual vm data is copied to the system store as it would be if you had for example an nfs image datastore.


4. this is indeed true, but you can safely ignore them
